events {}
http {
    server {
        listen 80;
        return 301 https://$host$request_uri;
    }
    server {
        listen 443 ssl;
        ssl_certificate     /etc/nginx/certs/tls.crt;
        ssl_certificate_key /etc/nginx/certs/tls.key;
        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;

        location / {
            proxy_pass         http://sspr:8080;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Forwarded-For   $remote_addr;
            proxy_set_header   X-Forwarded-Proto $scheme;
        }
    }
}
